from __future__ import annotations

import argparse
import re
from itertools import combinations
from pathlib import Path

import geopandas as gpd
import numpy as np
import pandas as pd
from shapely.geometry import Point
from shapely.ops import nearest_points


DEFAULT_INTERSECTIONS = "intersections_detected.csv"
DEFAULT_SHAPEFILE = "roads.shp"
DEFAULT_OUTPUT = "intersection_shapefile_comparison.csv"
LOCAL_SEARCH_RADII_M = (500.0, 2000.0, 5000.0)
ROAD_COLUMN_CANDIDATES = ("ref", "road", "road_name", "road_no", "route", "route_no", "name", "rd_name")


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments for the comparison workflow."""
    parser = argparse.ArgumentParser(
        description="Compare modeled intersections against intersections derived from a road shapefile."
    )
    parser.add_argument("--intersections", type=Path, default=Path(DEFAULT_INTERSECTIONS))
    parser.add_argument("--shapefile", type=Path, default=Path(DEFAULT_SHAPEFILE))
    parser.add_argument("--output", type=Path, default=Path(DEFAULT_OUTPUT))
    parser.add_argument("--road-column", type=str, default=None)
    return parser.parse_args()


def normalize_road_code(value: object) -> str:
    """Normalize road labels so codes such as 'N 2' and 'N2' compare equal."""
    if pd.isna(value):
        return ""
    return "".join(str(value).strip().upper().split())


def road_code_aliases(road_code: str) -> list[str]:
    """Return simple alternative spellings used by the shapefile."""
    normalized = normalize_road_code(road_code)
    if not normalized:
        return []

    aliases = [normalized]
    n_match = re.fullmatch(r"N(\d+[A-Z]?)", normalized)
    nh_match = re.fullmatch(r"NH(\d+[A-Z]?)", normalized)

    if n_match:
        aliases.append(f"NH{n_match.group(1)}")
    if nh_match:
        aliases.append(f"N{nh_match.group(1)}")

    return list(dict.fromkeys(aliases))


def haversine_m(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Compute the great-circle distance between two WGS84 points in meters."""
    earth_radius_m = 6_371_000.0
    lat1_rad, lon1_rad = np.radians(lat1), np.radians(lon1)
    lat2_rad, lon2_rad = np.radians(lat2), np.radians(lon2)
    delta_lat = lat2_rad - lat1_rad
    delta_lon = lon2_rad - lon1_rad
    a = (
        np.sin(delta_lat / 2.0) ** 2
        + np.cos(lat1_rad) * np.cos(lat2_rad) * np.sin(delta_lon / 2.0) ** 2
    )
    return float(2.0 * earth_radius_m * np.arcsin(np.sqrt(a)))


def to_3857_point(lat: float, lon: float) -> object:
    """Project one WGS84 point to Web Mercator for local metric buffering."""
    return gpd.GeoSeries([Point(lon, lat)], crs="EPSG:4326").to_crs(epsg=3857).iloc[0]


def to_4326_geometry(geometry_3857: object) -> object:
    """Project one Web Mercator geometry back to WGS84."""
    return gpd.GeoSeries([geometry_3857], crs="EPSG:3857").to_crs(epsg=4326).iloc[0]


def extract_points(geometry: object) -> list[tuple[float, float]]:
    """Extract point-like candidates from a geometry returned by a line intersection."""
    if geometry.is_empty:
        return []

    geom_type = geometry.geom_type
    if geom_type == "Point":
        return [(float(geometry.y), float(geometry.x))]
    if geom_type == "MultiPoint":
        return [(float(point.y), float(point.x)) for point in geometry.geoms]
    if geom_type == "LineString":
        centroid = geometry.centroid
        return [(float(centroid.y), float(centroid.x))]
    if geom_type == "MultiLineString":
        return [(float(line.centroid.y), float(line.centroid.x)) for line in geometry.geoms if not line.is_empty]
    if geom_type == "GeometryCollection":
        points: list[tuple[float, float]] = []
        for part in geometry.geoms:
            points.extend(extract_points(part))
        return points
    return []


def require_columns(df: pd.DataFrame, columns: list[str], label: str) -> None:
    """Validate that a table contains the required columns."""
    missing = [column for column in columns if column not in df.columns]
    if missing:
        raise ValueError(f"{label} is missing required columns: {missing}")


def load_intersections(path: Path) -> pd.DataFrame:
    """Load modeled intersections generated by the Assignment 3 pipeline."""
    intersections = pd.read_csv(path)
    require_columns(intersections, ["id", "name", "lat", "lon", "connected_roads"], "intersections_detected.csv")

    intersections = intersections.copy()
    intersections["lat"] = pd.to_numeric(intersections["lat"], errors="coerce")
    intersections["lon"] = pd.to_numeric(intersections["lon"], errors="coerce")
    intersections["connected_roads"] = intersections["connected_roads"].fillna("").astype(str)
    intersections["connected_roads_list"] = (
        intersections["connected_roads"]
        .map(normalize_road_code)
        .str.split("|")
        .map(lambda values: [value for value in values if value])
    )
    return intersections.dropna(subset=["lat", "lon"]).copy()


def infer_road_column(roads_gdf: gpd.GeoDataFrame, explicit_column: str | None) -> str:
    """Choose the shapefile column that best represents the road identifier."""
    if explicit_column:
        if explicit_column not in roads_gdf.columns:
            raise ValueError(f"Column '{explicit_column}' not found in shapefile: {list(roads_gdf.columns)}")
        return explicit_column

    lower_to_original = {column.lower(): column for column in roads_gdf.columns}
    for candidate in ROAD_COLUMN_CANDIDATES:
        if candidate.lower() in lower_to_original:
            return lower_to_original[candidate.lower()]

    raise ValueError(
        "Could not infer the road identifier column from the shapefile. "
        f"Available columns: {list(roads_gdf.columns)}"
    )


def load_roads(path: Path, explicit_road_column: str | None) -> tuple[gpd.GeoDataFrame, str, dict[str, object]]:
    """Load and normalize the shapefile and create one merged geometry per road code."""
    roads = gpd.read_file(path)
    if roads.empty:
        raise ValueError(f"The shapefile contains no records: {path}")
    if roads.crs is None:
        raise ValueError("The shapefile has no CRS information.")

    road_column = infer_road_column(roads, explicit_road_column)
    roads = roads.to_crs(epsg=4326).copy()
    roads[road_column] = roads[road_column].map(normalize_road_code)
    roads = roads[roads.geometry.notna()].copy()

    roads_3857 = roads.to_crs(epsg=3857)
    merged_geometries: dict[str, object] = {}
    for road_code, group in roads_3857.groupby(road_column):
        if road_code:
            merged_geometries[road_code] = group.geometry.union_all()

    return roads_3857, road_column, merged_geometries


def resolve_road_geometry(road_code: str, merged_geometries: dict[str, object]) -> tuple[str, object] | None:
    """Resolve a modeled road code to a matching shapefile geometry, including simple aliases."""
    for alias in road_code_aliases(road_code):
        geometry = merged_geometries.get(alias)
        if geometry is not None:
            return alias, geometry
    return None


def local_geometry(road_geometry_3857: object, center_3857: object, radius_m: float) -> object | None:
    """Clip a merged road geometry to a local search area around one modeled intersection."""
    search_area = center_3857.buffer(radius_m)
    if not road_geometry_3857.intersects(search_area):
        return None
    clipped = road_geometry_3857.intersection(search_area)
    return None if clipped.is_empty else clipped


def candidate_points_for_pair(
    model_lat: float,
    model_lon: float,
    road_a: str,
    road_b: str,
    merged_geometries: dict[str, object],
) -> list[dict[str, object]]:
    """Find local shapefile candidate points for one modeled road pair."""
    resolved_a = resolve_road_geometry(road_a, merged_geometries)
    resolved_b = resolve_road_geometry(road_b, merged_geometries)
    if resolved_a is None or resolved_b is None:
        return []

    code_a, geom_a = resolved_a
    code_b, geom_b = resolved_b
    model_point_3857 = to_3857_point(model_lat, model_lon)
    pair_label = f"{road_a}|{road_b}"
    resolved_pair = f"{code_a}|{code_b}"

    for radius_m in LOCAL_SEARCH_RADII_M:
        local_a = local_geometry(geom_a, model_point_3857, radius_m)
        local_b = local_geometry(geom_b, model_point_3857, radius_m)
        if local_a is None or local_b is None:
            continue

        intersection_points = extract_points(to_4326_geometry(local_a.intersection(local_b)))
        if intersection_points:
            return [
                {
                    "road_pair_used": pair_label,
                    "resolved_shapefile_pair": resolved_pair,
                    "match_method": "exact_intersection",
                    "shapefile_lat": lat,
                    "shapefile_lon": lon,
                }
                for lat, lon in intersection_points
            ]

        point_a, point_b = nearest_points(local_a, local_b)
        midpoint_4326 = to_4326_geometry(
            Point((point_a.x + point_b.x) / 2.0, (point_a.y + point_b.y) / 2.0)
        )
        return [
            {
                "road_pair_used": pair_label,
                "resolved_shapefile_pair": resolved_pair,
                "match_method": "nearest_midpoint",
                "shapefile_lat": float(midpoint_4326.y),
                "shapefile_lon": float(midpoint_4326.x),
            }
        ]

    return []


def best_match_for_intersection(intersection: pd.Series, merged_geometries: dict[str, object]) -> dict[str, object]:
    """Select the closest shapefile-based candidate for one modeled intersection."""
    model_lat = float(intersection["lat"])
    model_lon = float(intersection["lon"])
    candidates: list[dict[str, object]] = []

    for road_a, road_b in combinations(intersection["connected_roads_list"], 2):
        candidates.extend(candidate_points_for_pair(model_lat, model_lon, road_a, road_b, merged_geometries))

    if not candidates:
        return {
            "road_pair_used": "",
            "resolved_shapefile_pair": "",
            "match_method": "no_candidate_found",
            "shapefile_lat": np.nan,
            "shapefile_lon": np.nan,
            "delta_lat": np.nan,
            "delta_lon": np.nan,
            "difference_m": np.nan,
            "n_candidate_locations": 0,
        }

    best_candidate = min(
        candidates,
        key=lambda candidate: haversine_m(
            model_lat,
            model_lon,
            float(candidate["shapefile_lat"]),
            float(candidate["shapefile_lon"]),
        ),
    )

    shapefile_lat = float(best_candidate["shapefile_lat"])
    shapefile_lon = float(best_candidate["shapefile_lon"])
    return {
        **best_candidate,
        "delta_lat": shapefile_lat - model_lat,
        "delta_lon": shapefile_lon - model_lon,
        "difference_m": haversine_m(model_lat, model_lon, shapefile_lat, shapefile_lon),
        "n_candidate_locations": len(candidates),
    }


def build_comparison_table(intersections: pd.DataFrame, merged_geometries: dict[str, object]) -> pd.DataFrame:
    """Build the full comparison table written to the output CSV."""
    rows = []
    for _, intersection in intersections.iterrows():
        rows.append(
            {
                "intersection_id": int(intersection["id"]),
                "intersection_name": str(intersection["name"]),
                "connected_roads": str(intersection["connected_roads"]),
                "model_lat": float(intersection["lat"]),
                "model_lon": float(intersection["lon"]),
                **best_match_for_intersection(intersection, merged_geometries),
            }
        )

    comparison = pd.DataFrame(rows)
    return comparison.sort_values(["difference_m", "intersection_id"], na_position="last")


def main() -> None:
    """Run the comparison workflow and write the resulting CSV."""
    args = parse_args()
    base_dir = Path(__file__).resolve().parent

    intersections_path = args.intersections if args.intersections.is_absolute() else (base_dir / args.intersections)
    shapefile_path = args.shapefile if args.shapefile.is_absolute() else (base_dir / args.shapefile)
    output_path = args.output if args.output.is_absolute() else (base_dir / args.output)

    intersections = load_intersections(intersections_path)
    _, road_column, merged_geometries = load_roads(shapefile_path, args.road_column)
    comparison = build_comparison_table(intersections, merged_geometries)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    comparison.to_csv(output_path, index=False)

    print(f"Loaded {len(intersections)} modeled intersections.")
    print(f"Matched against shapefile road column: {road_column}")
    print(f"Wrote comparison CSV to: {output_path}")

    if comparison.empty:
        print("No intersection rows were available for comparison.")
        return

    print("\nTop 10 largest location differences (meters):")
    print(
        comparison[
            ["intersection_id", "intersection_name", "connected_roads", "match_method", "difference_m"]
        ]
        .head(10)
        .to_string(index=False)
    )


if __name__ == "__main__":
    main()
