from mesa import Agent
from enum import Enum
import numpy as np


# ---------------------------------------------------------------
class Infra(Agent):
    """
    Base class for all infrastructure components

    Attributes
    __________
    vehicle_count : int
        the number of vehicles that are currently in/on (or totally generated/removed by)
        this infrastructure component

    length : float
        the length in meters
    ...

    """

    def __init__(self, unique_id, model, length=0,
                 name='Unknown', road_name='Unknown'):
        super().__init__(unique_id, model)
        self.length = length
        self.name = name
        self.road_name = road_name
        self.vehicle_count = 0

    def step(self):
        pass

    def __str__(self):
        return type(self).__name__ + str(self.unique_id)


# ---------------------------------------------------------------
class Bridge(Infra):
    """
    Bridge that may be broken down for an entire simulation run.

    Attributes
    __________
    condition:
        condition of the bridge

    is_broken:
        whether the bridge is broken down for the current run

    total_wait_time: float
        the cumulative waiting time caused by this bridge over the run
    ...

    """

    def __init__(self, unique_id, model, length=0,
                 name='Unknown', road_name='Unknown', condition='Unknown'):
        super().__init__(unique_id, model, length, name, road_name)

        self.condition = condition
        self.total_wait_time = 0.0
        self.is_broken = self._sample_initial_breakdown()

    def _sample_initial_breakdown(self):
        """
        Decide once per run whether this bridge is broken down.

        The breakdown probability depends on the bridge condition and is
        provided by the scenario configuration in the model.
        """
        probability = self.model.scenario_probs.get(self.condition, 0.0)
        return self.model.random.random() < probability

    def sample_delay_time(self):
        """
        Draw a waiting time from the bridge-length-based delay distribution.
        """
        if self.length > 200:
            return self.model.random.triangular(1, 4, 2)
        if 50 < self.length <= 200:
            return self.model.random.uniform(45, 90)
        if 10 < self.length <= 50:
            return self.model.random.uniform(15, 60)
        if self.length <= 10:
            return self.model.random.uniform(10, 20)
        raise ValueError(f"Invalid bridge length: {self.length}")

    def get_average_delay_time(self):
        """
        Return the mean delay implied by the bridge's delay distribution.

        This expected value is used in routing so path selection reflects the
        average disruption caused by a broken bridge in the current run.
        """
        if self.length > 200:
            return (1 + 4 + 2) / 3
        if 50 < self.length <= 200:
            return (45 + 90) / 2
        if 10 < self.length <= 50:
            return (15 + 60) / 2
        if self.length <= 10:
            return (10 + 20) / 2
        raise ValueError(f"Invalid bridge length: {self.length}")

    def get_delay_time(self):
        """
        Return the wait caused by this bridge for the current vehicle arrival.

        If the bridge is not broken for this run, vehicles pass immediately.
        When the bridge is broken, each arriving vehicle draws its own delay
        from the length-based distribution.
        """
        if not self.is_broken:
            return 0.0

        delay_time = self.sample_delay_time()
        self.total_wait_time += delay_time
        return delay_time


# ---------------------------------------------------------------
class Link(Infra):
    pass


# ---------------------------------------------------------------
class Intersection(Infra):
    pass


# ---------------------------------------------------------------
class Sink(Infra):
    """
    Sink removes vehicles

    Attributes
    __________
    vehicle_removed_toggle: bool
        toggles each time when a vehicle is removed
    ...

    """
    vehicle_removed_toggle = False
    log_events = False

    def remove(self, vehicle):
        self.model.schedule.remove(vehicle)
        self.vehicle_removed_toggle = not self.vehicle_removed_toggle
        if self.log_events:
            print(str(self) + ' REMOVE ' + str(vehicle))


# ---------------------------------------------------------------

class Source(Infra):
    """
    Source generates vehicles

    Class Attributes:
    -----------------
    truck_counter : int
        the number of trucks generated by ALL sources. Used as Truck ID!

    Attributes
    __________
    generation_frequency: int
        the frequency (the number of ticks) by which a truck is generated

    vehicle_generated_flag: bool
        True when a Truck is generated in this tick; False otherwise
    ...

    """

    truck_counter = 0
    vehicle_generated_flag = False
    log_events = False

    def step(self):
        mean_arrivals = self.get_mean_arrivals_per_step()
        if mean_arrivals <= 0:
            self.vehicle_generated_flag = False
            return

        generated_count = int(self.model.np_random.poisson(mean_arrivals))
        self.vehicle_generated_flag = False
        for _ in range(generated_count):
            self.generate_truck()

    def get_mean_arrivals_per_step(self):
        """
        Return the expected number of truck arrivals for this source in one model step.
        """
        daily_truck_demand = float(getattr(self, "daily_truck_demand", 0.0) or 0.0)
        demand_scale = float(getattr(self.model, "demand_scale", 1.0))
        steps_per_day = float(getattr(self.model, "steps_per_day", 24 * 60))
        if steps_per_day <= 0:
            return 0.0
        return max(daily_truck_demand * demand_scale / steps_per_day, 0.0)

    def generate_truck(self):
        """
        Generates a truck, sets its path, increases the global and local counters
        """
        try:
            agent = Vehicle('Truck' + str(Source.truck_counter), self.model, self)
            if not agent.set_path():
                return

            self.model.schedule.add(agent)
            Source.truck_counter += 1
            self.vehicle_count += 1
            self.vehicle_generated_flag = True
            if self.log_events:
                print(str(self) + " GENERATE " + str(agent))
        except Exception as e:
            print("Oops!", e.__class__, "occurred.")


# ---------------------------------------------------------------
class SourceSink(Source, Sink):
    """
    Generates and removes trucks
    """
    pass


# ---------------------------------------------------------------
class Vehicle(Agent):
    """

    Attributes
    __________
    speed: float
        speed in meter per minute (m/min)

    step_time: int
        the number of minutes (or seconds) a tick represents
        Used as a base to change unites

    state: Enum (DRIVE | WAIT)
        state of the vehicle

    location: Infra
        reference to the Infra where the vehicle is located

    location_offset: float
        the location offset in meters relative to the starting point of
        the Infra, which has a certain length
        i.e. location_offset < length

    path_ids: Series
        the whole path (origin and destination) where the vehicle shall drive
        It consists the Infras' uniques IDs in a sequential order

    location_index: int
        a pointer to the current Infra in "path_ids" (above)
        i.e. the id of self.location is self.path_ids[self.location_index]

    waiting_time: int
        the time the vehicle needs to wait

    generated_at_step: int
        the timestamp (number of ticks) that the vehicle is generated

    removed_at_step: int
        the timestamp (number of ticks) that the vehicle is removed
    ...

    """

    # 48 km/h translated into meter per min
    speed = 48 * 1000 / 60
    # One tick represents 1 minute
    step_time = 1
    log_state_each_step = False

    class State(Enum):
        DRIVE = 1
        WAIT = 2

    def __init__(self, unique_id, model, generated_by,
                 location_offset=0, path_ids=None):
        super().__init__(unique_id, model)
        self.generated_by = generated_by
        self.generated_at_step = model.schedule.steps
        self.location = generated_by
        self.location_offset = location_offset
        self.pos = generated_by.pos
        self.path_ids = path_ids
        # default values
        self.state = Vehicle.State.DRIVE
        self.location_index = 0
        self.waiting_time = 0
        self.waited_at = None
        self.removed_at_step = None

    def __str__(self):
        return "Vehicle" + str(self.unique_id) + \
               " +" + str(self.generated_at_step) + " -" + str(self.removed_at_step) + \
               " " + str(self.state) + '(' + str(self.waiting_time) + ') ' + \
               str(self.location) + '(' + str(self.location.vehicle_count) + ') ' + str(self.location_offset)

    def set_path(self):
        """
        Set the origin destination path of the vehicle
        """
        self.path_ids = self.model.get_route(self.generated_by.unique_id)
        return self.path_ids is not None and len(self.path_ids) >= 2

    def step(self):
        """
        Vehicle waits or drives at each step
        """
        if self.state == Vehicle.State.WAIT:
            self.waiting_time = max(self.waiting_time - 1, 0)
            if self.waiting_time == 0:
                self.waited_at = self.location
                self.state = Vehicle.State.DRIVE

        if self.state == Vehicle.State.DRIVE:
            self.drive()

        """
        To print the vehicle trajectory at each step
        """
        if self.log_state_each_step:
            print(self)

    def drive(self):

        # the distance that vehicle drives in a tick
        # speed is global now: can change to instance object when individual speed is needed
        distance = Vehicle.speed * Vehicle.step_time
        distance_rest = self.location_offset + distance - self.location.length

        if distance_rest > 0:
            # go to the next object
            self.drive_to_next(distance_rest)
        else:
            # remain on the same object
            self.location_offset += distance

    def drive_to_next(self, distance):
        """
        vehicle shall move to the next object with the given distance
        """

        self.location_index += 1
        next_id = self.path_ids[self.location_index]
        next_infra = self.model.schedule._agents[next_id]  # Access to protected member _agents

        if isinstance(next_infra, Sink) and next_id == self.path_ids[-1]:
            # arrive at the sink
            self.arrive_at_next(next_infra, 0)
            self.removed_at_step = self.model.schedule.steps
            self.location.remove(self)
            return
        elif isinstance(next_infra, Bridge):
            self.waiting_time = next_infra.get_delay_time()
            if self.waiting_time > 0:
                # arrive at the bridge and wait
                self.arrive_at_next(next_infra, 0)
                self.state = Vehicle.State.WAIT
                return
            # else, continue driving

        if next_infra.length > distance:
            # stay on this object:
            self.arrive_at_next(next_infra, distance)
        else:
            # drive to next object:
            self.drive_to_next(distance - next_infra.length)

    def arrive_at_next(self, next_infra, location_offset):
        """
        Arrive at next_infra with the given location_offset
        """
        self.location.vehicle_count -= 1
        self.location = next_infra
        self.location_offset = location_offset
        self.location.vehicle_count += 1

# EOF -----------------------------------------------------------
